const templates={
 'Getting started':`Walk a first-time visitor through getting started.\n- start on the page as it loads and say what it is for in one line\n- find the getting-started or quick-start section and follow its first three steps\n- point out the one thing people usually miss\nTone: a developer showing a colleague, not a product demo.`,
 'Feature tour':`Tour the main features, one screen each.\n- open with what the app does and who it is for\n- visit each main section from the navigation, spending longest on the one people use most\n- end on where to go next\nTone: keep it brisk. Say what each screen is for, not every button on it.`,
 'Explain a docs page':`Explain what the main dashboard shows and how to read it.\n- start at the top and say what the page is for in one line\n- walk each panel in reading order: what the number or chart means and when to worry about it\n- point out the one control people should learn first\nTone: brisk and plain. Read the screen, do not describe every pixel.`,
 'How to do one task':`Show how to do one specific task: [name the task].\n- start where the task begins and say the goal\n- click through each step, saying what to look for before each click\n- show the result and how to tell it worked\nTone: short and to the point, one to two minutes at most.`,
 'Pricing and plans':`Walk through the pricing page.\n- start at the top with the plans and what separates them\n- point out what the free or lowest plan includes\n- scroll to any FAQ and cover the questions about billing\nTone: matter-of-fact, no sales pitch.`,
 'API reference':`Explain how to make the first API call from this reference page.\n- read the endpoint name and say what it does in one line\n- point out authentication, then the required parameters one by one\n- scroll to the example request and response and read the important fields aloud\nTone: a developer pairing with another developer. Precise and unhurried.`,
 'Compare options':`Compare the options this page offers and help someone choose.\n- start with what the options have in common\n- go through what separates them, spending longest on the differences that matter day to day\n- end with who each option is for\nTone: even-handed. Describe, do not sell.`};
const chips=document.getElementById('chips');let expanded=false;function renderChips(){chips.innerHTML=Object.keys(templates).slice(0,expanded?7:5).map(k=>`<button class="chip">${k}</button>`).join('');chips.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.getElementById('briefInput').value=templates[b.textContent];chips.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active')})}renderChips();document.getElementById('showMore').onclick=()=>{expanded=!expanded;document.getElementById('showMore').textContent=expanded?'⌃ Less':'▸ More';renderChips()};
document.querySelectorAll('.segmented button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.segmented button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');let script=btn.dataset.mode==='script';document.getElementById('briefArea').classList.toggle('hidden',script);document.getElementById('scriptArea').classList.toggle('hidden',!script)});
document.getElementById('lookToggle').onclick=()=>document.getElementById('lookPanel').classList.toggle('hidden');
document.querySelectorAll('.choice-pills').forEach(group=>group.querySelectorAll('button').forEach(b=>b.onclick=()=>{group.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));
document.querySelectorAll('.swatch').forEach(b=>b.onclick=()=>{document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
const modal=document.getElementById('modal');function closeModal(){modal.classList.add('hidden')}modal.addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop')||e.target.classList.contains('modal-close'))closeModal()});
document.getElementById('apiKeysBtn').onclick=()=>{document.getElementById('modalContent').innerHTML=`<button class="modal-close">×</button><h2>API keys</h2><p>Billed to your own accounts. Stored encrypted.</p>${[['Google AI Studio','Script writer','Writes with Gemini Flash, free. From aistudio.google.com.','connected · •••• 8F2A'],['Groq','Script writer (alt)','Writes with GPT-OSS 120B, free. From console.groq.com.','Not set'],['Deepgram','Voice','Speaks with Deepgram Aura, free. Word-level timestamps included.','Not set'],['ElevenLabs','Voice (alt)','Speaks with Eleven v3. Free plan for standard voices.','Not set']].map((x,i)=>`<div class="api-row"><div class="api-row-top"><div><b>${x[0]}</b><small>${x[1]} · ${x[2]}</small></div><span class="${i===0?'connected':'notset'}">${x[3]}</span></div><div class="api-input"><input type="password" placeholder="Paste your API key"><button>Save</button></div></div>`).join('')}<div class="modal-foot">Keys are encrypted at rest and never logged or shared with another provider. A shared free house key is used when you haven't connected one.</div>`;modal.classList.remove('hidden')};
document.getElementById('extensionBtn').onclick=()=>{document.getElementById('modalContent').innerHTML=`<button class="modal-close">×</button><h2>Chrome extension</h2><p>Bring the page as you see it. The extension uses your own Chrome session for login-protected pages and bot checks.</p><div class="extension-note"><span>◈</span><span>Chrome Web Store publishing is coming soon. For now, download the companion folder and choose <b>Load unpacked</b> at chrome://extensions.</span></div><button class="create-btn" style="margin-top:20px" onclick="closeModal()">Got it</button>`;modal.classList.remove('hidden')};
document.getElementById('previewVoice').onclick=function(){this.textContent='■ Playing…';setTimeout(()=>this.textContent='▶ Preview',1800)};
function progressView(){return `<div class="progress-shell"><div class="progress-head"><div><div class="eyebrow">VIDEO 0148</div><h1>Getting started with Acme</h1><p class="sub">Writing the script · under a minute left</p></div><button class="outline-btn">Cancel</button></div><div class="progress-card"><div class="overall"><div><b id="stageTitle">Dry-run against the target</b><small id="percent">89%</small></div><div class="bar"><i id="barFill"></i></div></div><div class="check-item done"><div class="checkmark">✓</div><div><b>Explore the target</b><small>1 screen · 214 elements worth pointing at</small></div></div><div class="check-item done"><div class="checkmark">✓</div><div><b>Write the narration</b><small>9 beats · 1,493 characters</small></div></div><div class="check-item active"><div class="spinner"></div><div><b>Dry-run against the target</b><small id="liveLine">b5: scrolls 0.1 screens in 0.6s (under)</small></div></div><div class="progress-note">Every selector, scroll, and camera move is checked against the live page before we spend a TTS credit.</div></div></div>`}
document.getElementById('createBtn').onclick=()=>{document.getElementById('newView').classList.add('hidden');let pv=document.getElementById('progressView');pv.classList.remove('hidden');pv.innerHTML=progressView();let n=0;let timer=setInterval(()=>{n++;let pct=Math.min(100,89+n*3);document.getElementById('percent').textContent=pct+'%';document.getElementById('barFill').style.width=pct+'%';let lines=['b5: scrolls 0.1 screens in 0.6s (under)','b6: target resolves exactly once · visible','b7: scrolls 0.8 screens in 1.9s (ok)','b9: target resolves exactly once · visible'];document.getElementById('liveLine').textContent=lines[n%lines.length];if(pct===100){clearInterval(timer);setTimeout(showReview,500)}},650)};
function showReview(){let pv=document.getElementById('progressView');pv.innerHTML=`<div class="review-head"><div><div class="eyebrow">SCRIPT READY</div><h1>Getting started with Acme</h1><p>Your script is ready. Read it, then make the video.</p><div class="badges"><span>9 beats</span><span>about 1:02</span><span class="good">✓ 9 of 9 runnable</span></div></div><button class="create-btn make-btn" onclick="startRender()">Make the video <span>→</span></button></div><div class="review-grid"><div><div class="fake-page"><div class="fake-nav"></div><div class="fake-lines"></div><div class="fake-card-row"><i></i><i></i><i></i></div><div class="fake-pointer">●</div></div><p class="caption">The page the script was written from.</p><div class="narration-card"><div class="section-head"><div><h2>Narration <span class="count">9 beats · 1,493 characters</span></h2></div><button class="outline-btn">Edit script</button></div>${['Acme helps your team ship reliable releases, without the release-day scramble.','First, open the project you want to work in. This is your home base for everything that follows.','The getting started guide lives here in the sidebar. Let’s follow the first three steps together.','Step one is to connect your repository. Look for the provider you use most often.','The thing people usually miss is this small environment selector. Set it before your first run.'].map((x,i)=>`<p><span>${i+1}</span>${x}</p>`).join('')}</div></div><aside><div class="checks-card"><h3>Checks</h3><div>✓ <b>1 screen</b> · 214 elements worth pointing at</div><div>✓ <b>9 of 9 beats runnable</b></div><div class="flag">i &nbsp; b5 scroll is short (reveal)</div></div></aside></div><div class="revision"><input placeholder="Want changes? Say what, for example: read the top three comments out loud"><button class="outline-btn">Rewrite</button><small>A new script comes back here for you to read.</small></div>`}
function startRender(){let pv=document.getElementById('progressView');pv.innerHTML=`<div class="progress-shell"><div class="progress-head"><div><div class="eyebrow">RENDERING VIDEO 0148</div><h1>Getting started with Acme</h1><p class="sub">Rendering · about 2 minutes left</p></div><button class="outline-btn">Cancel</button></div><div class="progress-card render-card"><div class="overall"><div><b id="renderTitle">Record</b><small id="renderPct">21%</small></div><div class="bar"><i id="renderFill" style="width:21%"></i></div></div><div class="check-item done"><div class="checkmark">✓</div><div><b>Narrate</b><small>1:02 of narration, every word timestamped</small></div></div><div class="check-item active"><div class="spinner"></div><div><b id="renderStage">Record</b><small id="renderLine">b2: scrolled 2.6 screens in 2.0s (reveal)</small></div></div><div class="check-item"><div class="empty-check"></div><div><b>Check every camera move</b><small>Audit crop rectangles and timing windows</small></div></div><div class="check-item"><div class="empty-check"></div><div><b>Render</b><small>Remotion composition · FFmpeg · 1080p60</small></div></div><div class="progress-note">You can leave this page. The video keeps going and shows up in the list when it is done.</div></div></div>`;let n=0;let t=setInterval(()=>{n++;let pct=21+n*7;document.getElementById('renderPct').textContent=pct+'%';document.getElementById('renderFill').style.width=pct+'%';if(n===6){document.getElementById('renderStage').textContent='Render';document.getElementById('renderLine').textContent='style: inset 7.0%, radius 22, captions word (29 cards)'}if(n>=11){clearInterval(t);showDone()}},500)}
function showDone(){document.getElementById('progressView').innerHTML=`<div class="review-head"><div><div class="eyebrow">VIDEO READY</div><h1>Getting started with Acme</h1><p>Your walkthrough is ready to share.</p><div class="badges"><span>1:02</span><span>1080p · 60 fps</span><span>Word captions</span><span class="good">Rendered just now · 18.4 MB</span></div></div><button class="create-btn make-btn">Download MP4 <span>↓</span></button></div><div class="done-grid"><div class="video-mock"><div class="play">▶</div><div class="caption-mock">Connect your repository <b>before</b> your first run.</div></div><aside><div class="checks-card"><h3>Checks</h3><div>✓ <b>9 camera moves</b>, each on the right subject at the right time</div><div>✓ Every cue landed within <b>18ms</b> of its spoken word</div><div class="audit-thumb">Camera audit sheet ↗</div></div><div class="retention">Kept for 3 days · until Sep 17, 2026</div></aside></div><div class="made-card"><h2>What it was made from</h2><p><b>Source URL</b> <a>https://docs.acme.dev/getting-started ↗</a></p><p><b>Brief</b> Walk a first-time visitor through getting started.<br> Tone: a developer showing a colleague, not a product demo.</p></div>`}

// Provider-aware BYOK controls. In production these values must be posted to the encrypted Laravel secrets endpoint,
// never stored in localStorage or exposed to jobs other than the selected provider.
const providerKeys = {};
function providerModal(){
  const providers=[
    ['deepgram','Deepgram Aura','Voice · free starter credits','Deepgram Aura returns audio; word timing is normalized by the worker.','aura-asteria-en'],
    ['elevenlabs','ElevenLabs','Voice · free plan / paid upgrade','Higher-fidelity voices and cloning. Word timing uses alignment in the worker.','eleven_multilingual_v2'],
    ['google','Google AI Studio','Script writer · free tier','Gemini Flash writes the structured beat timeline.','gemini-2.5-flash'],
    ['openai','OpenAI / ChatGPT','Script writer + optional TTS','Use GPT-4o mini for scripts or gpt-4o-mini-tts for speech.','gpt-4o-mini']
  ];
  document.getElementById('modalContent').innerHTML=`<button class="modal-close">×</button><div class="modal-kicker">SECURE PROVIDER CONNECTIONS</div><h2>API keys & providers</h2><p>Billed to your own accounts. Keys are sent only to the provider you choose and should be encrypted by the production API.</p><div class="provider-tabs"><button class="selected" data-tab="voice">Voice</button><button data-tab="writer">Writer</button><button data-tab="custom">Custom</button></div><div id="providerRows">${providers.map(p=>`<div class="provider-row" data-role="${p[0]==='deepgram'||p[0]==='elevenlabs'?'voice':'writer'}"><div class="provider-brand ${p[0]}">${p[1][0]}</div><div class="provider-main"><div class="provider-title"><b>${p[1]}</b><span class="provider-status" id="status-${p[0]}">Not connected</span></div><small>${p[2]}</small><p>${p[3]}</p><div class="provider-fields"><input type="password" id="key-${p[0]}" placeholder="Paste ${p[1]} API key"><input class="model-field" id="model-${p[0]}" value="${p[4]}" placeholder="Model / voice id"><button class="test-provider" data-provider="${p[0]}">Test & save</button></div><div class="provider-result" id="result-${p[0]}"></div></div></div>`).join('')}</div><div id="customProvider" class="custom-provider hidden"><label class="field-label">Provider name</label><input id="customName" placeholder="My company model"><label class="field-label">OpenAI-compatible base URL</label><input id="customBase" value="https://api.example.com/v1"><label class="field-label">Model name</label><input id="customModel" placeholder="my-model"><label class="field-label">API key</label><input id="customKey" type="password" placeholder="Paste the provider key"><button class="create-btn" id="saveCustom">Test custom provider</button><p class="modal-foot">The endpoint must accept POST /chat/completions using Bearer authentication. For TTS, configure a provider-specific audio endpoint in your workspace settings.</p></div><div class="modal-foot">Recommended free path: Deepgram Aura for voice + Google AI Studio Gemini Flash for writing. In the production Laravel app, store provider, encrypted key, model, base URL, status, and last_checked_at in an api_keys table. Never log raw keys.</div>`;
  modal.classList.remove('hidden');
  document.querySelectorAll('.provider-tabs button').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.provider-tabs button').forEach(x=>x.classList.remove('selected'));tab.classList.add('selected');let custom=tab.dataset.tab==='custom';document.getElementById('providerRows').classList.toggle('hidden',custom);document.getElementById('customProvider').classList.toggle('hidden',!custom);document.querySelectorAll('.provider-row').forEach(r=>r.classList.toggle('hidden',!custom&&r.dataset.role!==tab.dataset.tab))});
  document.querySelectorAll('.test-provider').forEach(btn=>btn.onclick=async()=>{const provider=btn.dataset.provider,key=document.getElementById('key-'+provider).value,model=document.getElementById('model-'+provider).value,result=document.getElementById('result-'+provider),status=document.getElementById('status-'+provider);btn.textContent='Testing…';result.textContent='';try{const r=await fetch('/api/providers/test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider,apiKey:key,voiceModel:model,model})}).then(x=>x.json());if(r.ok){providerKeys[provider]={apiKey:key,model};status.textContent='Connected · key verified';status.className='provider-status connected';result.textContent='✓ '+r.message}else result.textContent='! '+r.error}catch(e){result.textContent='! Could not reach the Signal API'}btn.textContent='Test & save'});
  document.getElementById('saveCustom').onclick=async()=>{const key=document.getElementById('customKey').value,baseUrl=document.getElementById('customBase').value,model=document.getElementById('customModel').value,result=document.querySelector('#customProvider .modal-foot');const r=await fetch('/api/providers/test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider:'custom',apiKey:key,baseUrl,model})}).then(x=>x.json());result.textContent=r.ok?'✓ '+r.message:'! '+r.error;if(r.ok)providerKeys.custom={apiKey:key,baseUrl,model}};
}
document.getElementById('apiKeysBtn').onclick=providerModal;
document.getElementById('previewVoice').onclick=async function(){const p=providerKeys.deepgram||providerKeys.elevenlabs;if(!p){providerModal();document.querySelector('.provider-tabs button[data-tab="voice"]').click();return}this.textContent='Testing…';const provider=providerKeys.deepgram?'deepgram':'elevenlabs';try{const r=await fetch('/api/tts/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider,apiKey:p.apiKey,voiceModel:p.model,voiceId:p.model,text:'Welcome to Signal. This is a real provider voice preview.'})}).then(x=>x.json());if(r.ok){const a=new Audio('data:'+r.mime+';base64,'+r.audioBase64);await a.play();this.textContent='▶ Preview'}else this.textContent='Try again'}catch(e){this.textContent='Try again'}};
